version: '3.8'

services:
  php:
    build:
       context: .
       dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=my_database

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=my_database

volumes:
  db_data: